name: Jenkins CI/CD

on:
  push:
    branches: [ agent-deployment ]
  pull_request:
    branches: [ agent-deployment ]

jobs:
  deploy:

    runs-on: [self-hosted, linux, x64, gci]

    steps:
      - name: Checks Out to Repo 
        uses: actions/checkout@v2

      - name: Install JDK
        run: |
          sudo apt install openjdk-11-jdk -y

      - name: Create config directory
        if: ${{ cancelled() == false && failure() == false }}
        run: |
          mkdir -p /home/${{secrets.USER}}/${{secrets.APP_PATH}}
      
      - name: Copy Source files
        if: ${{ cancelled() == false && failure() == false }}
        run: |
          cp agent.sh -t /home/${{secrets.USER}}/${{secrets.APP_PATH}}

      - name: Start Initial Agent
        env:
          JENKINS_BASE_URL: 'Http://localhost:5353'
          JENKINS_AGENT_SECRET: 'JENKINS AGENT SECRET'
          JENKINS_JNLP_PATH: 'computer/node%2Dinitial'
        if: ${{ cancelled() == false && failure() == false }}
        run: |
          chmod +x agent.sh
          ./agent.sh $JENKINS_BASE_URL $JENKINS_AGENT_SECRET $JENKINS_JNLP_PATH ${{secrets.SSH_PASSWORD}}
